version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Проброс порта Flask на localhost
    volumes:
      - ./app:/app   # Монтирование кода для быстрого обновления
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
      POSTGRES_DB: hotel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: