version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # вместо - ./app:/app
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
      - DB_NAME=hotel_db
      - DB_USER=hotel_user
      - DB_PASSWORD=hotel_password
      - FLASK_APP=run.py
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password
      POSTGRES_DB: hotel_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Используем именованный том

volumes:
  postgres_data:  # Определение именованного тома